= Agent configuration file

Agent configuration file is used by a self-registering agent to persist it's initial configuration which it requires in restart scenarios.

Agent looks for a file named *`nom-agent-config.yaml`* under the following directories in order:
. path set by `CONFIG_AGENT_CONFIG_PATH` environment variable
. `conf` directory under path set by `NEO4J_HOME` environment variable
. path set by `NEO4J_CONF` environment variable
. `.nom` directory under user home directory by default

[WARNING]
====
Agent reports an error while running in self-register mode such as `| ERROR | unable to load config from file error="open /home/.nom/nom-agent-config.yaml: no such file or directory"`. It is not an issue with agent operations but default behaviour to support restarts of agents which needs to llok for its initial configuration to connect to NOM server.

It is also possible to provide the entire configuration in configuration file but agent will override this file to only save configuration it requires to connect to NOM server.
Recommended way to configure agent is through environment variables as specified xref:./self-registered.adoc[here]
====

Following is a minimal agent configuration that is persisted by agent for server connection:
.nom-agent-config.yaml
[source, yaml]
----
token:
    url:
    clientId: "12fwe-1534f-3454-23dfgf"
    clientSecret: "cv34gh5657568jtyj768678=" 
----