= Neo4j instance requirements

In order to be managed by NOM a Neo4j instance **must**:

* be running a Neo4j Enterprise Edition v4.4.0 or higher (including all 5.x versions).

== Query log collection

[NOTE]
====

Log manager is only compatible with Neo4j version 5+.

====

For the query log collection feature to work correctly, `db.logs.query.enabled` needs to be set to `INFO` or `VERBOSE` in the link:https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/[neo4j.conf] file.
Also, make sure that the config value `db.logs.query.threshold` is set to a reasonable value, `0`, commented out or is removed. 
This setting acts as an lower bound for any completed query to appear in the logs. 
Thus, if this value is set too high, the queries you want to monitor might not get logged. 
Setting this value to zero will log every query.

== Metrics collection

For the metrics collection feature to work correctly. these configuration values need to be set in the link:https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/[neo4j.conf] file.:

=== For 4.4.x versions:

** `metrics.prometheus.endpoint=127.0.0.1:2004`

** `metrics.prometheus.enabled=true`

** `metrics.enabled=true`

** `metrics.filter=*`

** `metrics.jmx.enabled=true`

** `metrics.namespaces.enabled=true`

=== For 5.x versions:

** `server.metrics.prometheus.endpoint=127.0.0.1:2004`

** `server.metrics.prometheus.enabled=true`

** `server.metrics.enabled=true`

** `server.metrics.filter=*`

** `server.metrics.jmx.enabled=true`

** `server.metrics.namespaces.enabled=true`
