:description: This section describes the installation process for adding a managed DBMS to Neo4j Ops Manager.

= Installation process

Adding a DBMS in NOM’s terminology means to enable the monitoring of every instance in the DBMS by installing a NOM agent on the instance host and configuring it appropriately.

[[register]]
== Register agent

* Before adding the DBMS for NOM monitoring, an agent needs to be registered with NOM server which provides server communication configuration for the agent.
* An agent can be registered with NOM server -
** from NOM UI
*** Creation of agent requires name and description for the agent
*** Once registered the configuration for agent to communicate with NOM server will be:
**** `CONFIG_SERVER_ADDRESS=<server-address>`
**** `CONFIG_TOKEN_URL=<token_url>`
**** `CONFIG_TOKEN_CLIENT_ID=<agent-id>`
**** `CONFIG_TOKEN_CLIENT_SECRET=<agent-client-secret>`
*** Save these configurations securely for later to configure the agent
* Check if the instance of DBMS to be monitored has a supported version.
Only Neo4j versions from 4.4 on are supported.
* Before installing the agent to monitor an instance of the DBMS, make sure that the instance is up and running.
You can check the status with `neo4j status` command


[[install]]
== Agent installation

The following steps are required to install an agent:

* Standalone binaries (only linux and windows platform binaries are available)
** Download: https://neo4j.com/download-center/#ops-manager[Download]
** Extract the archive:
+
[source, terminal, role=noheader]
----
tar -xvzf <agent downloaded archive>
----
** Add the `bin` folder in the extracted directory to `PATH`
* To verify the installation, run the following command:
+
[source, terminal, role=noheader]
----
agent version
----
+
Which should output:
+
[source, terminal, role=noheader]
----
<agent name> <agent version> <agent revision>
----

* Make sure the agent version is equal to that of the NOM server.


[[configure]]
== Configure agent

An agent’s run configurations are provided through environment variables.
The following table lists configuration keys and values to be set for them:

[cols="<,<,<",options="header"]
|===
| Variable
| Description
| Example

| `CONFIG_SERVER_ADDRESS`
| Server GRPC Address
| server:9090

| `CONFIG_TOKEN_URL`
| Server Token URL
| +++https://server:8080/api/login/agent+++

| `CONFIG_TOKEN_CLIENT_ID`
| Client ID for the agent
|` 3ff98478-d6d2-4e1b-b816-e758c835f076`

| `CONFIG_TOKEN_CLIENT_SECRET`
| Client secret for the agent
| secret

| `CONFIG_TLS_TRUSTED_CERTS`
| PEM encoded trusted CA list ()
| `/path/to/a/pem/file`

| `CONFIG_LOG_LEVEL`
| Log level (debug,info,warn,error)
| info

| `CONFIG_LOG_FILE`
| Path to the log file
| `/var/log/nom-agent/log.txt`
|===

[NOTE]
====
Since agent-server communication needs to be encrypted, you need to configure the agent so that it trusts the server's certificates.
The file that contains the trusted certificate list (PEM encoded) can be specified through the `CONFIG_TLS_TRUSTED_CERTS` environment variable.
While most operating systems default to the system-wide trusted certificates, that's not the case on Windows.
For that reason, you must set this environment variable on Windows.
====

Apart from the start configuration above, for each of the monitored DBMS instance(s), the following environment variables needs to be set to allow the agent to access the instance:

[cols="<,<,<",options="header"]
|===
| Variable
| Description
| Example

| `CONFIG_INSTANCE_n_NAME`
| Name of nth instance
| my-instance-n

| `CONFIG_INSTANCE_n_BOLT_URI`
| Bolt URI for nth instance
| bolt://localhost:7687

| `CONFIG_INSTANCE_n_BOLT_USERNAME`
| Bolt user name for nth instance
| neo4j

| `CONFIG_INSTANCE_n_BOLT_PASSWORD`
| Bolt password for nth instance
| password
|===

[NOTE]
====
Agents are supposed to monitor only local instances and should not be configured to connect to remote instances.
====

[[running-agent]]
== Run an agent

An agent can run in two modes, console or service.
Best practice is to run an agent in service mode.

. Run an agent in console mode:
+
All configuration values for the agent should be set as environment variables before starting the agent
+
* Command:
+
[source, terminal, role=noheader]
----
agent console
----

. Run an agent in service mode:
+
To run an agent in service means that the agent process runs in the background and monitors the instance and this is the recommended way.
The agent lifecycle is handled by the operating system service manager.
+
* Install the service for linux (systemd):
+
** Run
+
[source, terminal, role=noheader]
----
agent service install
----
** Execute
+
[source, terminal, role=noheader]
----
systemctl edit neo4j-ops-manager-agent.service
----
+
and set environment variables by either setting Environment or EnvironmentFile options.
For example, using the Environment options, the override file looks as follows:
+
[source, terminal, role=noheader]
----
[Service]
Environment="CONFIG_SERVER_ADDRESS=<server grpc address>"
Environment="CONFIG_TOKEN_URL=<server http login url>"
Environment="CONFIG_TOKEN_CLIENT_ID=<client id>"
Environment="CONFIG_TOKEN_CLIENT_SECRET=<client secret>"
Environment="CONFIG_TLS_TRUSTED_CERTS=</path/to/trusted/certs/pem/file>"
Environment="CONFIG_LOG_FILE=</path/to/nom-agent/log.txt>"
Environment="CONFIG_INSTANCE_1_NAME=<instance name>"
Environment="CONFIG_INSTANCE_1_BOLT_URI=<bolt uri of the local instance>"
Environment="CONFIG_INSTANCE_1_BOLT_USERNAME=<local instance user name>"
Environment="CONFIG_INSTANCE_1_BOLT_PASSWORD=<local instance password>"
----
+
** Start your service
+
[source, terminal, role=noheader]
----
systemctl start neo4j-ops-manager-agent.service
----
+
or
+
[source, terminal, role=noheader]
----
systemctl stop neo4j-ops-manager-agent.service
----
** Logs are available, using journalctl, via
+
[source, terminal, role=noheader]
----
journalctl -u neo4j-ops-manager-agent
----
+
* Install the service for Windows:
** Run
+
[source, terminal, role=noheader]
----
agent service install
----
+
** Open registry editor and navigate to `HKLM\SYSTEM\CurrentControlSet\Services\neo4j-ops-manager-agent`.
** Create a key of type `REG_MULTI_SZ` named `Environment` and add your environment variables, each on a separate line:
+
[source, terminal, role=noheader]
----
CONFIG_SERVER_ADDRESS=<server grpc address>
CONFIG_TOKEN_URL=<server http login url>
CONFIG_TOKEN_CLIENT_ID=<client id>
CONFIG_TOKEN_CLIENT_SECRET=<client secret>
CONFIG_TLS_TRUSTED_CERTS=</path/to/the/trusted/certs/pem>
CONFIG_LOG_FILE=</path/to/nom-agent/log.txt>
CONFIG_INSTANCE_1_NAME=<instance name>
CONFIG_INSTANCE_1_BOLT_URI=<bolt uri of the local instance>
CONFIG_INSTANCE_1_BOLT_USERNAME=<local instance user name>
CONFIG_INSTANCE_1_BOLT_PASSWORD=<local instance password>
----
+
** Start your service
+
[source, terminal, role=noheader]
----
agent service start
----
+
* To uninstall the service
+
[source, terminal, role=noheader]
----
agent service uninstall
----

[[add-single]]
== Add a single instance

To add a single instance of the DBMS to monitor:
* Install the agent, as above.
* Configure the environment variables required by the agent.
* Run the agent.

[[add-cluster]]
== Add a cluster

To add a DBMS cluster to monitor, for every instance of the cluster:
* Install the agent, as above.
* Configure the environment variables required by the agent.
* Run the agent.
