= Monitoring concepts
:description: This section describes the concepts that are important to understand how Neo4j Ops Manager can be used for monitoring systems.

This section describes important concepts for understanding how to optimally use Neo4j Ops Manager to monitor systems.

== Conditions

A **Condition** specifies the constraints when the monitored entity reaches a certain state.
Conditions are periodically evaluated, and evaluation results are persisted.

There are two **types** of Conditions:

* **Event-based Conditions**: a Condition evaluates to **true** when a specific event is generated by the monitoring subsystem.
Examples: "Unreachable/Offline agents detected", "Incompatible agent connected".
* **Metric-based Conditions**: a Condition evaluates to **true** when the metric(s) assigned to it change in a way so that its expression evaluates to **true**.
Example: "Host CPU usage exceeds 80% longer than 2 minutes".

A Condition can have a **grace time**. If present, grace time means that this Condition would only evaluate to **true** if all its **Evaluations** during the grace time evaluated to **true**.

If a Condition evaluates to **true**, Ops Manager lets the administrator know about that, as follows:

* Alerts are generated, which are shown in the NOM UI as banners, alert counts and alert lists.
* Notifications are generated, which result in a message being sent to one of the defined targets.

Conditions can be managed per DBMS in the Conditions tab of the Alerts page.

See xref:./alerts-conditions.adoc[Alerts and Conditions] on how to manage Conditions.

== Alerts

**Alerts** are shown in the NOM UI to notify the administrator about Conditions that evaluated to **true**.

In case there are Alerts in the managed system, Ops Manager provides following information about them:

* Total count of Alerts is displayed in the sidebar.
* Alert count per DBMS is displayed in the DBMS dropdown (for all accessible DBMSs) and the sidebar (for the currently selected DBMS).
* Alert banner is displayed, allowing the administrator to show Alerts details or DBMSs metrics.
* Detailed alert information is available from the Alerts page of the DBMS or from the Home page (in the Alert panel of the selected DBMS).

See xref:./alerts-conditions.adoc[Alerts and Conditions] on how to manage Alerts.

== Notifications

While Alerts are only displayed in the NOM browser page, Notifications enable sending information about triggered Conditions to external systems like email servers or other messaging systems.

See xref:./notifications.adoc[Notifications] on how to manage Notifications, Channels and Targets.
