= Monitoring concepts
:description: This section describes the concepts that are important to understand how Neo4j Ops Manager can be used for monitoring systems.

This section describes important concepts for understanding how to optimally use Neo4j Ops Manager to monitor systems.

== Conditions

A **condition** specifies the constraints when the monitored entity reaches a certain state.
Conditions are periodically evaluated, and evaluation results are persisted.

There are two **types** of conditions:

* **Event-based conditions**: a condition evaluates to **true** when a specific event is generated by the monitoring subsystem.
Examples: "Unreachable/Offline agents detected", "Incompatible agent connected".
* **Metric-based conditions**: a condition evaluates to **true** when the metric(s) assigned to it change in a way so that its expression evaluates to **true**.
Example: "Host CPU usage exceeds 80% longer than 2 minutes".

A condition can have a **grace time**.
If present, grace time means that this condition only evaluates to **true** if all its **Evaluations** during the grace time evaluate to **true**.

If a condition evaluates to **true**, Ops Manager lets the administrator know in the following way:

* Alerts are generated and shown in the NOM UI as banners, alert counts, and alert lists.
* Notifications are generated and a message is sent to one of the defined targets.

Conditions can be managed per DBMS in the conditions tab of the Alerts page.

See xref:./alerts-conditions.adoc#_managing_alerts[Managing alerts] on how to manage conditions.

== Alerts

**Alerts** are shown in the NOM UI to notify the administrator about conditions that evaluate to **true**.

In case there are alerts in the managed system, Ops Manager provides following information about them:

* Total count of alerts is displayed in the sidebar.
* Alert count per DBMS is displayed in the DBMS dropdown (for all accessible DBMSs) and the sidebar (for the currently selected DBMS).
* Alert banner is displayed, allowing the administrator to show alerts details or DBMSs metrics.
* Detailed alert information is available from the Alerts page of the DBMS or from the Home page (in the Alerts panel of the selected DBMS).

See xref:./alerts-conditions.adoc#_managing_conditions[Managing conditions] on how to manage alerts.

== Notifications

While alerts are only displayed in the NOM browser page, notifications enable sending information about triggered conditions to external systems, such as email servers or other messaging systems.

See xref:./notifications.adoc[Notifications] on how to manage notifications, channels and targets.
