:description: This section describes the update process for the NOM server.
= Server update

[NOTE]
====
Before starting the update process, it is recommended to back up your existing NOM installation folder.
====

[[server-version-notes]]
== Version specific notes

=== 1.5

This version introduces multi-user capabilities. As part of this move, the product analytics and crash analytics opt-out toggles have moved to a global setting accessible only by the NOM server admin.

To configure the opt-out toggles, please refer to *xref:../installation/server.adoc#config_ref[Server configuration reference
]*

=== 1.4

The initial startup of 1.4 after update may take longer than usual, especially if the persistence store contains a large amount of query log data.

This is due to additions to the query log model which require existing data to be migrated.

=== 1.3
[IMPORTANT]
====

All metrics will be deleted as part of the migration that runs on update to version 1.3.

This is due to a major change to the metric storage model making previous metrics incompatible with this version. 

====

[[server-linux]]
== On Linux

. Back up any files you've modified inside the current NOM server directory.
This usually includes `etc/neo4j-ops-manager-server.service` and any files inside `certificates/` directories.
. Download the latest NOM server package for your platform.
. Stop the NOM server by running `systemctl stop neo4j-ops-manager-server`.
. Extract the downloaded package into the existing installation directory.
. Copy the backed up files back into their corresponding locations.
. Start the NOM server by running `systemctl start neo4j-ops-manager-server`.
. Verify that the server is operating as expected by checking the logs.

[[server-windows]]
== On Windows

. Back up any files you've modified inside the current NOM server directory.
This usually includes `bin/server.xml` and any files inside `certificates/` directories.
. Download the latest NOM server package for your platform.
. Stop the NOM server by running `./bin/server.exe stop` inside the current NOM server directory.
. Extract the downloaded package into the existing installation directory.
. Copy the backed up files back into their corresponding locations.
. Start the NOM server by running `./bin/server.exe start`.
. Verify that the server is operating as expected by checking the logs.