:description: This section provides the prerequisites for Neo4j Ops Manager.

= Prerequisites

The NOM Server and Agents can be installed via downloading their respective packages from the link:https://neo4j.com/download-center[Neo4j Download Center] and placing them on the machines you want to run them on.
The Nom Server is designed to run on TLS-protected channels.
For that reason, you need to prepare a certificate and private key to secure server-agent communication.
The same certificate needs to be used for all agent installations.

*NOM Server*

* Java 17
* Key pair and certificate (as a PKCS12 file) to be used for TLS protected endpoints.

*Persistence DBMS:*

* Neo4j 4.4 Enterprise Edition
* At least 10 GB free disk space
* For minimum requirements, see also link:/operations-manual/current/installation/requirements/[Operations Manual -> System requirements].
* NOM comes with a license to run a Neo4j DBMS with up to 4 cores of CPU and up to 16 GB of RAM for the use as NOMs persistence.

Whilst an AuraDB Professional or Enterprise could be used for NOM persistence, consideration should be given to the following:

* The AuraDB instance should be for exclusive use of the NOM server
* The NOM server and persistence should ideally be located on the same LAN segment to avoid performance being impacted by WAN traffic
* Future product developments may require features not currently available in AuraDB

We plan to make NOMaaS available in the future
