= User Management (Administrators)
:description: This section describes the user management in Neo4j Ops Manager.

*User Management* allows setting up NOM users for persons who are in charge of managing
the Neo4j deployment and reflecting their roles by assigning appropriate access levels.

These tasks can only be accomplished by a NOM user who has the role *NOM Admin*.

[NOTE]
====
The default NOM user `admin` has the role *NOM Admin* and is therefore can be used to create new NOM users
(including other *Administrators*) and configure their access to NOM features.
====

The NOM user management is performed in the *Administrators* section of the NOM settings page.

== NOM User Administration Tasks

=== Creating a user

Click on *"Create user"* button to open the sidebar containing the tabs *"User info"* and *"DBMS access control"*.

==== Assigning Access Level On Features

If a user has the role *NOM admin* (see checkbox on the *"User info"* tab), it will have full feature access, for
all DBMSs. Therefore, the tab *"DBMS access control"* is not relevant for *NOM admins*.

Other users will have the role *Administrator* assigned. In this case, access to every feature can be given explicitly or
implicitly by assigning access levels to a DBMS glob pattern. Access levels for global features can be set on the
*"User info"* tab and DBMS-specific features can be secured on the *"DBMS access control"*.
See the following table for permission description.


|===
|NOM Feature (scope) |Access levels |Description

|*Agent* (global)
|No access, view, edit
|Access to the *"Agents"* page of the NOM settings area.

|*Status* (DBMS-specific)
|View, edit
|Access to the *"Status"* page for assigned DBMS(s).

|*Security* (DBMS-specific)
|No access, view, edit
|Access to the *"Security panel"* page for assigned DBMS(s).

|*Status* (DBMS-specific)
|No access, view
|Access to the *"Logs"* page for assigned DBMS(s).

|*Upgrades* (DBMS-specific)
|No access, View, edit
|Access to the *"Upgrade"* page for assigned DBMS(s).
|===

[IMPORTANT]
====
If DBMS is renamed or migrated after being assigned explicit permissions, the permissions will remain unchanged.
====

==== Working with glob patterns

Should the Neo4j deployment have many DBMSs, it can be efficient to assign DBMS-specific permissions to a set
of DBMSs with a single line in the permission table. The glob patterns are checked against the DBMS name, which
can be set using NOM.

The glob syntax used in NOM supports the following wildcards: `*`, `?` and `[...]`. For a description of how these
wildcards work see for example https://en.wikipedia.org/wiki/Glob_(programming)#Syntax[this wikipedia article]

[NOTE]
====
*Rules for multiple permissions on a DBMS:*

1. If several glob patterns match a DBMS, the permissions of all the matching globs are combined in a way that for every
feature the most restrictive access level is applied. *Example*: for a user, a glob pattern `\*` defines access level "Edit" for the "Security"
feature, whereas another glob pattern `*PROD*` defines access level "View" for the same feature. User's resulting access level
to the feature "Security" will be "View" since it is more restrictive.
2. If permissions are explicitly assigned to a DBMS, they always *as a whole* take precedence over permissions assigned to a glob
pattern that matches this DBMS name. This means, that the permissions assigned to a glob pattern are *ignored* completely.
====

=== Modifying a user

Locate the user to be modified, and use the tabs *"User info"* and *"DBMS access control"* to modify user. All
modifications performed are persisted when the *"Save"* button is clicked. Clicking *"Cancel"* removes undoes
the modifications. This also applies to removing assigned DBMS or glob patterns from the table in *"DBMS access control"*.
Until being saved or cancelled, removed entries are marked visually (grayed out).

[NOTE]
====
A user with role *NOM Admin* can not degrade her role to *Administrator*.
====

=== Removing a user

Locate the user to be removed, click it and press the "Remove user" button at the bottom of the sidebar.

[NOTE]
====
User can not remove himself.
====

[NOTE]
====
Should user modification or removal result in globs being unused (e.g. not referenced by other users), these globs will be removed
as well.
====
